
export const ItemTypes = {
  SUBRECORD: 'SUBRECORD',
  TARGET_SUBRECORD: 'TARGET',
  SOURCE_SUBRECORD: 'SOURCE'
};

export const DuplicateDatabaseStates = {
  FETCH_NEXT_DUPLICATE_ONGOING: 'FETCH_NEXT_DUPLICATE_ONGOING',
  SKIP_PAIR_ONGOING: 'SKIP_PAIR_ONGOING',
  MARK_AS_NON_DUPLICATE_ONGOING: 'MARK_AS_NON_DUPLICATE_ONGOING',
  READY: 'READY'
};