
export const ItemTypes = {
  SUBRECORD: 'SUBRECORD',
  TARGET_SUBRECORD: 'TARGET',
  SOURCE_SUBRECORD: 'SOURCE',
  MERGED_SUBRECORD: 'MERGED',
  SUBRECORD_ROW: 'SUBRECORD_ROW'
};

export const SubrecordActionTypes = {
  BLOCK: 'BLOCK',
  MERGE: 'MERGE',
  COPY: 'COPY'
};
