
export const ItemTypes = {
  SUBRECORD: 'SUBRECORD',
  TARGET_SUBRECORD: 'TARGET',
  SOURCE_SUBRECORD: 'SOURCE',
  MERGED_SUBRECORD: 'MERGED',
  SUBRECORD_ROW: 'SUBRECORD_ROW'
};

export const DuplicateDatabaseStates = {
  FETCH_NEXT_DUPLICATE_ONGOING: 'FETCH_NEXT_DUPLICATE_ONGOING',
  SKIP_PAIR_ONGOING: 'SKIP_PAIR_ONGOING',
  MARK_AS_NON_DUPLICATE_ONGOING: 'MARK_AS_NON_DUPLICATE_ONGOING',
  MARK_AS_MERGED_ONGOING: 'MARK_AS_MERGED_ONGOING',
  READY: 'READY'
};

export const SubrecordActionTypes = {
  BLOCK: 'BLOCK',
  MERGE: 'MERGE',
  COPY: 'COPY',
  UNSET: 'UNSET'
};

export const CommitMergeStates = {
  COMMIT_MERGE_NOT_STARTED: 'COMMIT_MERGE_NOT_STARTED',
  COMMIT_MERGE_ONGOING: 'COMMIT_MERGE_ONGOING',
  COMMIT_MERGE_ERROR: 'COMMIT_MERGE_ERROR',
  COMMIT_MERGE_COMPLETE: 'COMMIT_MERGE_COMPLETE'
};

export const RecordSaveStatus = {
  'UNSAVED': 'UNSAVED',
  'SAVED': 'SAVED',
  'SAVE_ONGOING': 'SAVE_ONGOING',
  'SAVE_FAILED': 'SAVE_FAILED'
};
